<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartAlpha.Core\SmartAlpha.Core.csproj" />
    <ProjectReference Include="..\SmartAlpha.Data\SmartAlpha.Data.csproj" />
    <ProjectReference Include="..\SmartAlpha.Analytics\SmartAlpha.Analytics.csproj" />
    <ProjectReference Include="..\SmartAlpha.Reporting\SmartAlpha.Reporting.csproj" />
  </ItemGroup>

</Project>
